cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [

	path('add-product-to-cart/<slug:slug>/', views.AddProductCartView, name="add_product_to_cart"),
	path("remove-product-from-cart/<slug:slug>/", views.RemoveProductCartView, name="remove_product_cart"),
	path("cart-detail/<int:user_id>/", views.CartDetailView, name="cart_detail"),
	path("delete-cart/<int:card_id>/", views.DeleteCartView, name="delete_cart"),

]

checkout/urls.py
from django.urls import path
from . import views

app_name = "checkout"

urlpatterns = [

	path("checkout", views.CheckoutView, name="checkout"),
	path("pay/<int:order_id>/", views.PayView, name="pay"),
	path("confirm-payment/<int:order_id>/", views.ConfirmPaymentView, name="confirm_payment"),
	path("complete-order/<int:order_id>/", views.CompleteOrderView, name="complete_order"),
	
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("search", views.SearchView, name="search"),
	path("category/<str:category>/", views.CategoryView, name="category"),

	path("faqs/", views.FaqsView, name="faqs"),
	path("privacy/", views.PrivacyView, name="privacy"),
	path("terms-and-condition/", views.TermsConditionView, name="termscondition"),
	path("shipping/", views.ShippingView, name="shipping"),

	path("admin-user/", views.AdminUserView, name="admin_user"),


	path("userlogout/", views.UserLogoutView, name="userlogout"),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf import settings
from django.conf.urls.static import static

from main.sitemaps import ProductSitemap


sitemaps = {

	"product": ProductSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),

	path("", include("main.urls")),
    path("", include("shop.urls")),
	path("", include("product.urls")),
	path("", include("cart.urls")),
	path("", include("checkout.urls")),
    path("", include("app_user.urls")),
    path("", include("order.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [

	path("product-detail/<slug:slug>/", views.ProductDetailView, name="product_detail"),
	path("buy-now/<slug:slug>/", views.BuyNowView, name="buy_now"),
	path("product-review/<slug:slug>", views.ProductReviewView, name="product_review"),
	path("all-product/", views.AllProductView, name="all_products"),

]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [

	path("shop/", views.ShopView, name="shop"),

]

cart/models.py
from django.db import models
from product.models import Product, ProductQuantity
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class Cart(models.Model):
	product_quantitys = models.ManyToManyField(ProductQuantity, through="CartProductQuantityConnector", through_fields=("cart", "product_quantity"),)
	total_price = models.IntegerField(blank=True, null=True)
	total_products = models.IntegerField(blank=True, null=True)
	cart_id = models.CharField(max_length=150)
	user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
	pub_date = models.DateTimeField(default=timezone.now)
	
	
	def __str__(self):
		#return self.cart_id
		return str(self.user.username)

		
class CartProductQuantityConnector(models.Model):
	cart = models.ForeignKey(Cart, on_delete=models.CASCADE, default="")
	product_quantity = models.ForeignKey(ProductQuantity, on_delete=models.CASCADE, default="")
	pub_date = models.DateTimeField(default=timezone.now)

cart/views.py
from django.shortcuts import render, get_object_or_404

from product.models import Product, ProductQuantity, Quantity
from cart.models import Cart, CartProductQuantityConnector

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate

from main.views import UserCreatorFunc
from django.contrib import messages

from geopy.distance import great_circle
import requests
import random


# Create your views here.

def GetDistance():
	ip_data= requests.get('http://ipinfo.io/json').json()
	client_latlon = ip_data['loc']
	#base_latlon = (6.4474, 3.3903)
	base_latlon = (10.5105, 7.4165)
	#base_latlon = (9.0579,7.4951)
	
	
	return great_circle(client_latlon, base_latlon).miles



def AddProductCartView(request, slug):
	quantity = 1
	quantity = Quantity.objects.create(quantity=quantity)
	quantity.save()
		
	user_id = request.user.id
		
	cart = get_object_or_404(Cart, user__pk=user_id)
	product = get_object_or_404(Product, slug=slug)
	
	#code for checking if the customer orders more than the available quantity
	if product.quantity < 1:
		messages.success(request, "Sorry, There are not enough amout of this product.")
		return HttpResponseRedirect(reverse("main:index"))
			
	else:
		product.quantity -= 1
		product.save()
		#distance = GetDistance()
		#total_shipping_charge = product.shipping_charge * distance
		total_shipping_charge = 0

		product_quantity = ProductQuantity.objects.create(product=product, quantity=quantity, total_shipping_charge=total_shipping_charge)
		product_quantity.save()
		
		cp = CartProductQuantityConnector(cart=cart, product_quantity=product_quantity)
		cp.save()
		messages.success(request, "Product Successfully Added to Cart")
	
		return HttpResponseRedirect(reverse("main:index"))


def RemoveProductCartView(request, slug):
	cart = get_object_or_404(Cart, user__pk=request.user.id)
	product_quantitys = cart.product_quantitys.all()
	for item in product_quantitys:
		if item.product.slug == slug:
			product = get_object_or_404(Product, slug=slug)
			product_quantity = get_object_or_404(ProductQuantity, quantity=item.quantity, product=product)
			product_quantity.delete()
			cart.save()
		else:
			pass
			
	return HttpResponseRedirect(reverse("cart:cart_detail", args=(request.user.id,)))



def CartDetailView(request, user_id):
	if request.method == "POST":
		pass
		
	else:
		UserCreatorFunc(request)

		cart = get_object_or_404(Cart, user__pk=request.user.id)

		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			qty = int(str(item.quantity))
			total_price += (item.product.price * qty) + (item.total_shipping_charge * qty)
	
		total_price = "{:,.2f}".format(total_price)
		section_two = sorted(Product.objects.all().order_by("-pub_date"), key=lambda x: random.random())[:6]
		context = {"total_price": total_price, "product_quantitys": product_quantitys, "cart": cart, "section_two": section_two}
		return render(request, 'cart/cart_detail.html', context)



def DeleteCartView(request):
	pass

cart/templates/cart/cart_detail.html
 {% extends 'main/base.html' %}
 {% load static %}
 

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
    {{ message }}
    </div>
    {% endfor %}
{% endif %} 
 

    <div class="ps-page--simple">
        <div class="ps-section--shopping ps-shopping-cart">
            <div class="container" style="margin-top: -50px">
                <div class="ps-section__header">
                    <h1>Your Shopping Cart</h1>
                </div>
                <div class="ps-section__content" style="margin-top: -115px">
                    <div class="table-responsive">
                        <table class="table">
                            <thead style="background-color: #3c3c3c">
                                <br>
                                <tr style="color: #fff">
                                    <th>PRODUCT(S)</th>
                                    <th>PRICE</th>
                                    <th>QUANTITY</th>
                                    <th></th>
                                </tr>
                                <br>
                            </thead>
                            <tbody>
                                <br><br>
                            	{% if product_quantitys %}
                               
                                	{% for item in product_quantitys %}
                                	<tr style="background-color: #f2f2f2;">
                                    <td>
                                        <div class="ps-product--cart">
                                            <div class="ps-product__thumbnail"><a href="{% url 'product:product_detail' item.product.slug %}"><img src="{{ item.product.image_1.url }}" alt=""></a></div>
                                            <div class="ps-product__content"><a href="{% url 'product:product_detail' item.product.slug %}">{{ item.product.name }}</a>
                                                
                                            </div>
                                        </div>
                                    </td>

                                    <td class="price" style="padding-top: 25px">₦{{ item.product.price }}</td>
                                    <td style="padding-top: 25px">
                                    	<strong>{{ item.quantity }}</strong>
                                    </td>
                                    <td style="padding-top: 25px"><a href="{% url 'cart:remove_product_cart' item.product.slug %}"><i class="icon-cross"></i></a></td>


									</tr>

                                    {% endfor %}
                                   
                                    {% else %}
                                    	<tr>
                                    	<td>Nothing yet!</td>
                                    	<td>Nothing yet!</td>
                                    	<td>Nothing yet!</td>
                                    	<td></td>
                                    	</tr>
                                    {% endif %}
                                
                             </tbody>
                        </table>
                        
                    </div>
                    <br />
                    <br />
                    <br />
                    <p>Select cancel or delete if you change your mind over a particular furniture or intend to replace then. The total cost of the products you have selected will be automatically generated and you can then proceed to make payments.</p>
                    <div class="ps-section__cart-actions"><a class="ps-btn" href="{% url 'shop:shop' %}"><i class="icon-arrow-left"></i> Back to Shop</a></div>
                </div>
                <div class="ps-section__footer">
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12 ">
                            <div class="ps-block--shopping-total">
                                <div class="ps-block__header">
                                    <p>Your Items<span>{{ product_quantitys.product.count }}</span></p>
                                </div>
                                <div class="ps-block__content">
                                    <ul class="ps-block__product">
                                    	{% if product_quantitys %}
                                    		{% for item in product_quantitys %}
                                        		<li><span class="ps-block__shops">Name: {{ item.product.name }}</span><span class="ps-block__shippings">Quanity: {{ item.quantity }}</span><span class="ps-block__shippings">Price: ₦{{ item.product.price }}</span>
                                        		</li>
                                        	{% endfor %}
                                        {% else %}
                                        	<li>Sorry, Nothing Yet!</li>
                                        {% endif %}
                                    </ul>
                                    <h3>Total<span> ₦{{ total_price }}</span></h3>
                                </div>
                            </div>
                            
                            {% if total_price == 0 %}
                            	<a class="ps-btn ps-btn--fullwidth" href="{% url 'main:index' %}">Visit Store</a>
                            {% else %}
                            	<a class="ps-btn ps-btn--fullwidth" href="{% url 'checkout:checkout' %}">Proceed to checkout</a>
                            {% endif %}

                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <p>Please, carefully verify your 'Order List' to ensure that you have your selected products on the list. Then Click on the 'Proceed to Checkout' button to make payment and place your Order. In case you still want to add other items to your list, scroll up, click the 'Back to Shop' button and then proceed to add other products from any category of your choice. Once again! check to confirm all items on your list.</p>
                </div>
            </div>
        </div>
    </div>
    
    
    
    
    <div class="ps-product-list ps-clothings">
            <div class="ps-container">
            		<div class="ps-section__header">
		                <h3>You may also buy some of these.</h3>
		            </div>
                    <div class="ps-section__content">
                    <div class="ps-carousel--nav owl-slider" data-owl-auto="false" data-owl-loop="false" data-owl-speed="10000" data-owl-gap="0" data-owl-nav="true" data-owl-dots="true" data-owl-item="7" data-owl-item-xs="2" data-owl-item-sm="2" data-owl-item-md="3" data-owl-item-lg="4" data-owl-item-xl="6" data-owl-duration="1000" data-owl-mousedrag="on">
                    	{% if section_two %}
                    		{% for item in section_two %}
				                <div class="ps-product">
				                    <div class="ps-product__thumbnail"><a href="{% url 'product:product_detail' item.slug %}"><img src="{{ item.image_1.url }}" alt=""></a>
				                        <div class="ps-product__badge"><div class="ps-product__badge" style="background-color: {{ item.tag_title_color }}">{{ item.tag_title }}</div></div>
				                        <ul class="ps-product__actions">
				                            <li><a href="{% url 'cart:add_product_to_cart' item.slug %}" data-toggle="tooltip" data-placement="top" title="Add to cart"><i class="icon-bag2"></i></a></li>
				                            <li><a href="#" data-placement="top" title="Quick View" data-toggle="modal" data-target="#{{ item.slug }}"><i class="icon-eye"></i></a></li>
				                            <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-heart"></i></a></li>
				                            <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-chart-bars"></i></a></li>
				                        </ul>
				                    </div>
				                    <div class="ps-product__container"><a class="ps-product__vendor" href="#">{{ item.category }}</a>
				                        <div class="ps-product__content"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
				                            <div class="ps-product__rating">
				                                <select class="ps-rating" data-read-only="true">
				                                    <option value="1">1</option>
				                                    <option value="1">2</option>
				                                    <option value="1">3</option>
				                                    <option value="1">4</option>
				                                    <option value="2">5</option>
				                                </select><span>01</span>
				                            </div>
				                            <p class="ps-product__price sale">₦{{ item.price }} <del>₦{{ item.old_price }} </del></p>
				                        </div>
				                        <div class="ps-product__content hover"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
				                            <p class="ps-product__price sale">₦{{ item.price }} <del>₦{{ item.old_price }} </del></p>
				                        </div>
				                    </div>
				                </div>
				                
				             {% endfor %}
				             
				          {% else %}
				          		 <div class="ps-product">
				          		 	<p>Sorry, Nothing yet!</p>
				          		 </div>
				         	{% endif %}
                    </div>
                </div>
            </div>
        </div>
        
         </div>
    </div>
    
    
  {% endblock %}