cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [

	path('add-product-to-cart/<slug:slug>/', views.AddProductCartView, name="add_product_to_cart"),
	path("remove-product-from-cart/<slug:slug>/", views.RemoveProductCartView, name="remove_product_cart"),
	path("cart-detail/<int:user_id>/", views.CartDetailView, name="cart_detail"),
	path("delete-cart/<int:card_id>/", views.DeleteCartView, name="delete_cart"),

]

checkout/urls.py
from django.urls import path
from . import views

app_name = "checkout"

urlpatterns = [

	path("checkout", views.CheckoutView, name="checkout"),
	path("pay/<int:order_id>/", views.PayView, name="pay"),
	path("confirm-payment/<int:order_id>/", views.ConfirmPaymentView, name="confirm_payment"),
	path("complete-order/<int:order_id>/", views.CompleteOrderView, name="complete_order"),
	
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf import settings
from django.conf.urls.static import static

from main.sitemaps import ProductSitemap


sitemaps = {

	"product": ProductSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),

	path("", include("main.urls")),
    path("", include("shop.urls")),
	path("", include("product.urls")),
	path("", include("cart.urls")),
	path("", include("checkout.urls")),
    path("", include("app_user.urls")),
    path("", include("order.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

checkout/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from main.views import UserCreatorFunc, get_state_shipping, ray_randomiser
from cart.models import Cart
from order.models import Order
from app_user.models import AppUser
from product.models import Product


# Create your views here.

def CheckoutView(request):
	user_id = request.user.id
	if request.method == "POST":
		name = request.POST.get("name")
		phone = request.POST.get("phone")
		email = request.POST.get("email")
		address = request.POST.get("address")
		delivery_state = request.POST.get("delivery_state")

		order_note = request.POST.get("order_note")

		try:
			app_user = AppUser.objects.get(user=request.user)
			app_user.name = name
			app_user.phone = phone
			app_user.email = email
			app_user.address = address
			app_user.delivery_state = delivery_state
			app_user.order_note = order_note
			app_user.save()

		except:
			app_user = AppUser.objects.create(user=request.user, name=name, phone=phone, email=email, address=address, delivery_state=delivery_state)
			app_user.order_id = ray_randomiser()
			app_user.save()
		
		cart = get_object_or_404(Cart, user__pk=request.user.id)

		delivery_state = app_user.delivery_state

		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (get_state_shipping(item.product.slug, delivery_state) * int(str(item.quantity)))
			#total_quantity += int(str(item.quantity))
		
		#messages.success(request, "Dear " +name+ ", you have successfully placed your order." )
		cart.total_price = total_price
		cart.save()

		order = Order.objects.create(app_user=app_user, cart=cart, order_note=order_note)
		order.save()
		#total_price = total_price * total_quantity
		
		
		
		#paystack comes in here
		#return HttpResponse("i got here moda fucker!")
		
		return HttpResponseRedirect(reverse("checkout:complete_order", args=(order.id,)))


		
	else:
		UserCreatorFunc(request)

		cart = Cart.objects.get(user__pk=request.user.id)# get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()

		if cart.product_quantitys.count() == 0:
			messages.success(request, "Sorry, You have nothing to checkout. Add Some!" )
			return HttpResponseRedirect(reverse("shop:shop"))

		else:

			try:
				app_user = AppUser.objects.get(user__pk=request.user.id)
			except:
				app_user = None

			

			total_price = 0
			total_quantity = 0

			for item in product_quantitys:
				total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))
				
			if total_price == 0:
				return HttpResponseRedirect(reverse("checkout:checkout"))
			elif total_price > 0:
				if app_user:
					total_price = "{:,.2f}".format(total_price)
					context = {"app_user": app_user, "total_price": total_price, "cart": cart, "product_quantitys": product_quantitys}
				else:
					total_price = "{:,.2f}".format(total_price)
					context = {"total_price": total_price, "cart": cart, "product_quantitys": product_quantitys}
				return render(request, 'checkout/checkout.html', context)
			else:
				return HttpResponseRedirect(reverse("main:index"))





def PayView(request, order_id):
	UserCreatorFunc(request)
	order = get_object_or_404(Order, id=order_id, cart__user=request.user)

	context = {"order": order}
	return render(request, 'checkout/pay.html', context)




def ConfirmPaymentView(request, order_id):
	if request.method == "POST":
		status = "Confirmed"

		order = get_object_or_404(Order, id=order_id, cart__user=request.user)
		order.status = status	
		order.save()

		#here we reduce product quantity as planned
		cart = order.cart

		product_quantitys = cart.product_quantitys.all()
		for item in product_quantitys:
			product = Product.objects.get(slug=item.product.slug)
			product.quantity -= int(str(item.quantity))
			product.save()
		

		logout(request)
		return HttpResponseRedirect(reverse("main:index"))
		
	else:
		UserCreatorFunc(request)
		context = {}
		return render(request, 'checkout/confirm_payment.html', context)




def CompleteOrderView(request, order_id):
	if request.method == "POST":
		status = "Confirmed"

		order = get_object_or_404(Order, id=order_id, cart__user=request.user)
		order.status = status	
		order.save()

		#here we reduce product quantity as planned
		cart = order.cart

		product_quantitys = cart.product_quantitys.all()
		for item in product_quantitys:
			product = Product.objects.get(slug=item.product.slug)
			product.quantity -= int(str(item.quantity))
			product.save()
		

		logout(request)
		messages.success(request, "Dear " +order.app_user.name  +", you have successfully placed your order." )

		return HttpResponseRedirect(reverse("main:index"))
		
	else:
		UserCreatorFunc(request)
		cart = get_object_or_404(Cart, user__pk=request.user.id)

		try:
			app_user = AppUser.objects.get(user__pk=request.user.id)
		except:
			app_user = None

		delivery_state = app_user.delivery_state

		product_quantitys = cart.product_quantitys.all()
		shippings = []

		total_price = 0
		total_quantity = 0

		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (get_state_shipping(item.product.slug, delivery_state) * int(str(item.quantity)))
			shippings.append("{:,.2f}".format((get_state_shipping(item.product.slug, delivery_state) * int(str(item.quantity)))))

		shippings_product_quantitys = zip(product_quantitys, shippings)
		total_price = "{:,.2f}".format(total_price)

		context = {"app_user": app_user, "total_price": total_price, "cart": cart, "shippings_product_quantitys": shippings_product_quantitys}
		return render(request, 'checkout/complete.html', context)

checkout/templates/checkout/checkout.html
 {% extends 'main/base.html' %}
{% load static %}


{% block content %}


		<div class="ps-checkout ps-section--shopping">
            <div class="container" style="margin-top: -50px">
                <div class="ps-section__header">
                    <h1 style="color: #666;">Place Your Order</h1>
                    <br />
                    <p>We would like to get some basic information from you. Kindly fill in your name, phone number, address and your preffered state of delivery. This will help us to keep proper records of your transaction with us. You will not need to fill these details for subsequent transactions.</p>
                </div>
                <div class="ps-section__content">
                    <form class="ps-form--checkout" method="post" enctype="multipart/form-data">
				{% csrf_token %}
                    
                        <div class="row">
                            <div class="col-xl-7 col-lg-8 col-md-12 col-sm-12  ">
                                <div class="ps-form__billing-info">
                                    <h3 class="ps-form__heading" style="color: #666;">Your Details:</h3>
                                    <div class="form-group">
                                        <label>Your Full Name<sup>*</sup>
                                        </label>
                                        <div class="form-group__content">
                                            <input style="text-align: left" name="name" class="form-control" type="text" value="{{ app_user.name }}" required="required">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Your Phone Number
                                        </label>
                                        <div class="form-group__content">
                                            <input style="text-align: left" name="phone" class="form-control" value="{{ app_user.phone }}" type="text" required="required">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Your Email Address<sup>*</sup>
                                        </label>
                                        <div class="form-group__content">
                                            <input style="text-align: left" name="email" class="form-control" value="{{ app_user.email }}" type="email" required="required">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Your Address<sup>*</sup>
                                        </label>
                                        <div class="form-group__content">
                                            <textarea name="address" class="form-control" rows="7" placeholder="Please enter your correct address">{{ app_user.address }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Delivery State
                                        </label>
                                        {% if app_user.delivery_state == "abia" %}
                                            <select name="delivery_state" id="select" class="form-control">
                                                <option value="abia" selected="selected">Abia</option>
                                                <option value="adamawa">Adamawa</option>
                                                <option value="akwaibom">Akwa Ibom</option>
                                                <option value="anambra">Anambra</option>
                                            </select>
                                        {% elif app_user.delivery_state == "adamawa" %}
                                            <select name="delivery_state" id="select" class="form-control">
                                               <option value="abia">Abia</option>
                                                <option value="adamawa" selected="selected">Adamawa</option>
                                                <option value="akwaibom">Akwa Ibom</option>
                                                <option value="anambra">Anambra</option>
                                            </select>

                                        {% elif app_user.delivery_state == "akwaibom" %}
                                            <select name="delivery_state" id="select" class="form-control">
                                               <option value="abia">Abia</option>
                                                <option value="adamawa">Adamawa</option>
                                                <option value="akwaibom" selected="selected">Akwa Ibom</option>
                                                <option value="anambra">Anambra</option>
                                            </select>

                                        {% elif app_user.delivery_state == "anambra" %}
                                            <select name="delivery_state" id="select" class="form-control">
                                               <option value="abia">Abia</option>
                                                <option value="adamawa">Adamawa</option>
                                                <option value="akwaibom">Akwa Ibom</option>
                                                <option value="anambra" selected="selected">Anambra</option>
                                            </select>


                                        {% else %}
                                            <select name="delivery_state" id="select" class="form-control">
                                               <option value="abia">Abia</option>
                                                <option value="adamawa">Adamawa</option>
                                                <option value="akwaibom">Akwa Ibom</option>
                                                <option value="anambra">Anambra</option>
                                            </select>

                                        {% endif %}
                                    </div>

                                    <h3 class="mt-40" style="color: #666;"> Addition information</h3>
                                    <div class="form-group">
                                        <label>Order Notes</label>
                                        <div class="form-group__content">
                                            <textarea name="order_note" class="form-control" rows="7" placeholder="Please enter any special notes for delivery.">{{ app_user.order_note }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card col-xl-5 col-lg-4 col-md-12 col-sm-12  ">
                                <div class="ps-form__total">
                                    <h3 class="ps-form__heading" style="color: #666;">Your Order</h3>
                                    <div class="content">
                                        <div class="ps-block--checkout-total">
                                            <div class="ps-block__header">
                                            </div>
                                            <div class="ps-block__content">
                                                <table class="table ps-block__products">
                                                    <tbody>
                                                    	{% if product_quantitys %}
                                                        <ul>
                                                    		{% for item in product_quantitys %}
                                                                
                                                                    <li>
                                                                        <small>Name: {{ item.product.name }}</small><br />
                                                                    </li>
                                                                    <li>
                                                                        <small>Quantity: {{ item.quantity }}</small><br />
                                                                    </li>
                                                                    <li>
                                                                        <small>Price: {{ item.product.price }}</small><br />
                                                                    </li>

                                                                    <hr>

				                                              {% endfor %}
				                                              
				                                              {% else %}
				                                              	 <tr>
				                                                    <td>
				                                                    	<p>Sorry, Nothing Yet!</p>
				                                                    </td>
				                                                   </tr>
                                                                </ul>
				                                              {% endif %}
                                                    </tbody>
                                                </table>
                                                <h3 style="color: #666;">Total <span>₦{{ total_price }}</span></h3>
                                            </div>
                                        </div><br />
                                        <p>For every order you make, the shipping cost is calculated and added to your total bill. Our shipping rates are very considerate.</p>
                                        <button class="ps-btn ps-btn--fullwidth">Proceed!</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <p></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
 {% endblock %}

checkout/templates/checkout/complete.html
 {% extends 'main/base.html' %}
{% load static %}
  


{% block content %}
<div class="container text-centers">
	<br><br> 
    <div class="row container">
      <br />
      <p>Welcome to the Payment Page. We have verified your order list and added the shipping cost to the cost of items in your cart. we will need you to forward your unique order ID to us, after payment, so we can track your transaction and get your order ready for delivery. The accepted payment method is the bank transfer method. The details of the receiving account is on your screen. Call us if there is anything you want us to clarify.</p>
    </div>
    <br />
    <br />
        <div class="row container">

          <div class="card col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <div class="ps-form__total">
              <br>
                <h3 class="ps-form__heading" style="text-align: left; color: #666;">Your Order with Shipping Fee!</h3>
                <div class="content">
                    <div class="ps-block--checkout-total">
                        <div class="ps-block__header">
                        </div>
                        <div class="ps-block__content">
                            <table class="table ps-block__products container">
                                <tbody style="text-align: left;">
                                  {% if shippings_product_quantitys %}
                                    <ul style="text-align: left;">
                                    {% for item, shipping in shippings_product_quantitys %}
                                            
                                                <li>
                                                    <small>Name: {{ item.product.name }}</small><br />
                                                </li>
                                                <li>
                                                    <small>Quantity: {{ item.quantity }}</small><br />
                                                </li>
                                                <li>
                                                    <small>Price: {{ item.product.price }}</small><br />
                                                </li>
                                                <li>
                                                    <small>Shipping Charge: {{ shipping }}</small><br />
                                                </li>

                                                <hr>

                                  {% endfor %}
                                  
                                  {% else %}
                                     <tr>
                                        <td>
                                          <p>Sorry, Nothing Yet!</p>
                                        </td>
                                       </tr>
                                            </ul>
                                  {% endif %}
                                </tbody>
                            </table>
                            <h3 style="text-align: left; color:  #666;">Total <span>₦{{ total_price }}</span></h3>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card col-xl-6 col-lg-6 col-md-6 col-sm-12" style="text-align: left;">
          <div class="ps-form__total">
              <br>
          <p>

            <b style="font-size: 26px; margin-top: 35px">Make Payments to:</b>
            <br />
            <strong>Bank:</strong> Zenith Bank
            <br />
            <strong>Account Name:</strong> Interior Woodwork Limited.
            <br />
            <strong>Account Number:</strong> 0123 332 232
            <br />
            <br />
            <br />
            <strong style="font-size: 26px;">Order Id: {{ app_user.order_id }}</strong>
          </p>
          <p><br>You may proceed to make payment, so we can process your order.<br />We are also open to answer your questions; <br /><br />Contact us: <a href="tel:+2348099999068"><h2 style="color: #666;">(+234) 809 999 9068</h2></a></p>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <br><br> 
          <button class="ps-btn col-md-6 col-sm-12">Complete!</button> 
          <br><br> 
          <p>Why choose the transfer option? It’s true, a couple of persons will want to ask this question. We want to intimate you with the fact that over the years, we have gathered from our transactions with clients that; paying via transfer is the safest. You will not have to expose your card information and other sensitive details that can grant a third party or any fraudster the opportunity to exploit you. We are not just interested in your satisfaction, but also want to build a bid of trust and integrity with you. </p>
        </form>


        </div>

      </div>

  </div>
</div>
<br><br><br>
<hr>


{% endblock %}

checkout/templates/checkout/confirm_payment.html
 {% extends 'main/base.html' %}
{% load static %}
  


{% block content %}
<div class="container text-center">
	<br><br> 
        <div class="row">
         
          <div class="col-md-12 col-sm-12">

          <h2>Confirm Payment</h2>
          
          <hr>
 <form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<br><br> 
	<button class="ps-btn col-md-6 col-sm-12">Confirm</button> 
	<br><br> 
	<p>Please acknowledge that you have just made payment for your order.
    <h2 style="color: green;">(by clicking the 'confirm' button)</h2>
    <br />So we can be able to process your request as soon as possible.
  </p>


</form>
</div>
</div>
</div>
<br><br><br>
<hr>


{% endblock %}

checkout/templates/checkout/pay.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<br><br>
      <div class="container text-center">
        <div class="row">
          
          <div class="col-md-12 col-sm-12">
          <h4>Make Payment</h4>
          <hr>
          <br><br>
          <form>
			  <script src="https://js.paystack.co/v1/inline.js"></script>
			  <button type="button" onclick="payWithPaystack()" class="col-md-6 col-sm-12 ps-btn"> Pay </button> 
        <p><br>You may proceed to make payment, so we can process your order.<br />We are also open to answer your questions; <br /><br />Contact us: <a href="tel:+2348099999068"><h2>(+234) 809 999 9068</h2></a></p>
			</form>


        </div>

          </div>
        </div>
      </div>
      <br><br><br>
    <hr>
    



<!-- place below the html form -->
<!-- place below the html form -->
<script>
  function payWithPaystack(){
    var handler = PaystackPop.setup({
      key: 'pk_test_63f455ebba60b2058709180e31a9936c418588d7',
      email: '{{ order.app_user.email }}',
      amount: {{ order.cart.total_price }} * 100,
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
      metadata: {
         custom_fields: [
            {
                display_name: "{{ order.app_user.name }}",
                variable_name: "{{ order.app_user.name }}",
                value: "{{ order.app_user.phone }}"
            }
         ]
      },
      callback: function(response){
          alert('success. transaction ref is ' + response.reference);
          window.location.href = "{% url 'checkout:confirm_payment' order.id %}";
      },
      onClose: function(){
          alert('window closed');                                                  
      }
    });
    handler.openIframe();
  }
</script>

{% endblock %}