cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [

	path('add-product-to-cart/<slug:slug>/', views.AddProductCartView, name="add_product_to_cart"),
	path("remove-product-from-cart/<slug:slug>/", views.RemoveProductCartView, name="remove_product_cart"),
	path("cart-detail/<int:user_id>/", views.CartDetailView, name="cart_detail"),
	path("delete-cart/<int:card_id>/", views.DeleteCartView, name="delete_cart"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("search", views.SearchView, name="search"),
	path("category/<str:category>/", views.CategoryView, name="category"),

	path("faqs/", views.FaqsView, name="faqs"),
	path("privacy/", views.PrivacyView, name="privacy"),
	path("terms-and-condition/", views.TermsConditionView, name="termscondition"),
	path("shipping/", views.ShippingView, name="shipping"),

	path("admin-user/", views.AdminUserView, name="admin_user"),


	path("userlogout/", views.UserLogoutView, name="userlogout"),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf import settings
from django.conf.urls.static import static

from main.sitemaps import ProductSitemap


sitemaps = {

	"product": ProductSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),

	path("", include("main.urls")),
    path("", include("shop.urls")),
	path("", include("product.urls")),
	path("", include("cart.urls")),
	path("", include("checkout.urls")),
    path("", include("app_user.urls")),
    path("", include("order.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [

	path("product-detail/<slug:slug>/", views.ProductDetailView, name="product_detail"),
	path("buy-now/<slug:slug>/", views.BuyNowView, name="buy_now"),
	path("product-review/<slug:slug>", views.ProductReviewView, name="product_review"),
	path("all-product/", views.AllProductView, name="all_products"),

]

main/views.py
import random
import string
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from product.models import Product
from django.contrib import messages
from cart.models import Cart
from order.models import Order
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User


# Create your views here.


def get_state_shipping(product_slug, delivery_state):
	product = Product.objects.get(slug=product_slug)

	if delivery_state == "abia":
		state_shipping = product.abia_shipping

	elif delivery_state == "adamawa":
		state_shipping = product.adamawa_shipping

	elif delivery_state == "akwaibom":
		state_shipping = product.akwaibom_shipping

	elif delivery_state == "anambra":
		state_shipping = product.anambra_shipping

	else:
		state_shipping = 0




	return state_shipping 




def ray_randomiser(length=6):
	landd = string.ascii_letters + string.digits
	return ''.join((random.choice(landd) for i in range(length)))




def UserCreatorFunc(request):
	if request.user.is_active:
		user = request.user
		user = User.objects.get(id=user.id)
		user_checker = authenticate(username=user.username, password=user.password)
		#pass
		#return HttpResponse("issues ooo!")
	else:
		#return HttpResponse("i reached here ooo!")
		fake_username = "%s" % (ray_randomiser())
		fake_password = "%s" % (ray_randomiser())
		user = User.objects.create(username=fake_username)
		user.save()
		user.set_password(fake_password)
		user.save()
		user_checker = authenticate(username=fake_username, password=fake_password)
		
		if user.is_active:
			login(request, user_checker)
		else:
			pass

		cart = Cart.objects.create(user=user, pub_date=timezone.now())
		cart.user = user
		cart.save()


def IndexView(request):

	if request.method == "POST":
		pass
		
		
	else:
		UserCreatorFunc(request)
		
		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))
	
		product = Product.objects.all()

		all_products = sorted(Product.objects.all().order_by("-pub_date"), key=lambda x: random.random())
		section_one = sorted(Product.objects.filter(section="section_one").order_by("-pub_date"), key=lambda x: random.random())[:10]
	
		#return HttpResponse(section_four)
		total_price = "{:,.2f}".format(total_price)
		context = {"total_price": total_price, "product_quantitys": product_quantitys, "product": product, "all_products": all_products, "section_one": section_one}
		return render(request, 'main/index.html', context)




def CategoryView(request, category):
	if request.method == "POST":
		return HttpResponseRedirect(reverse("main:index"))
		
		
	else:
		UserCreatorFunc(request)

		products = Product.objects.filter(category=category)

		product_one = Product.objects.all()
		product_two = Product.objects.all()

		#product_one = Product.objects.filter(category=category)
		#product_two = Product.objects.filter(category=category)

		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))

		total_price = "{:,.2f}".format(total_price)
		context = {"category": category, "total_price": total_price, "product_quantitys": product_quantitys, 'product_one': product_one, "product_two": product_two}
		return render(request, 'main/category.html', context)







def SearchView(request):
	if request.method == "POST":
		query = request.POST.get('query')
		category = request.POST.get('category')
		if category == None:
			category = "ALL"
			products = Product.objects.filter(name__icontains=query)

		elif category == "ALL":
			products = Product.objects.filter(name__icontains=query)

		else:
			products = Product.objects.filter(name__icontains=query, category=str(category))
		
		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))

		total_price = "{:,.2f}".format(total_price)
		context = {"total_price": total_price, "product_quantitys": product_quantitys, 'products': products}
		return render(request, 'product/all_product.html', context)

		
		
	else:
		return HttpResponseRedirect(reverse("main:index"))
	





def FaqsView(request):
	if request.method == "POST":
		return HttpResponseRedirect(reverse("main:index"))
		
		
	else:
		UserCreatorFunc(request)
		
		products = Product.objects.all()[:10]

		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))

		total_price = "{:,.2f}".format(total_price)
		context = {"total_price": total_price, "product_quantitys": product_quantitys, 'products': products}
		return render(request, 'main/faqs.html', context)


def PrivacyView(request):
	if request.method == "POST":
		return HttpResponseRedirect(reverse("main:index"))
		
		
	else:
		UserCreatorFunc(request)
		
		products = Product.objects.all()[:10]

		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))

		total_price = "{:,.2f}".format(total_price)
		context = {"total_price": total_price, "product_quantitys": product_quantitys, 'products': products}
		return render(request, 'main/privacy.html', context)



def TermsConditionView(request):
	if request.method == "POST":
		return HttpResponseRedirect(reverse("main:index"))
		
		
	else:
		UserCreatorFunc(request)
		
		products = Product.objects.all()[:10]

		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))

		total_price = "{:,.2f}".format(total_price)

		context = {"total_price": total_price, "product_quantitys": product_quantitys, 'products': products}
		return render(request, 'main/terms.html', context)



def ShippingView(request):
	if request.method == "POST":
		return HttpResponseRedirect(reverse("main:index"))
		
		
	else:
		UserCreatorFunc(request)
		
		products = Product.objects.all()[:10]

		cart = get_object_or_404(Cart, user__pk=request.user.id)
		product_quantitys = cart.product_quantitys.all()
		total_price = 0
		total_quantity = 0
		for item in product_quantitys:
			total_price += (item.product.price * int(str(item.quantity))) + (item.total_shipping_charge * int(str(item.quantity)))


		total_price = "{:,.2f}".format(total_price)
		
		context = {"total_price": total_price, "product_quantitys": product_quantitys, 'products': products}
		return render(request, 'main/shipping.html', context)




def  AdminUserView(request):
	if request.user.is_superuser == True:
		if request.method == "POST":
			return HttpResponseRedirect(reverse("main:index"))
			
			
		else:
			
			orders = Order.objects.all().order_by("-pub_date")

			context = {"orders": orders}
			return render(request, 'main/admin_user.html', context)

	else:
		return HttpResponse("Not Authorised!, Contact ICT Unit(Interior Woodwork Limited)")		












def UserLogoutView(request):
	logout(request)
	return HttpResponseRedirect(reverse("index"))

main/templates/main/admin_user.html
<!DOCTYPE html>
<html>

	<head>
		<title>Admin User Dashboard</title>
	</head>

	<body>

		<div class="container">

			<div class="row">
				<h1>Admin User Dashboard:</h1>
				<hr>
			</div>
			<br />
			<br />
			<br />

			<div class="row">
				{% if orders %}
					{% for item in orders %}
						<small><b>Name:</b> {{ item.app_user.name }}</small><br />
						<small><b>Phone:</b> {{ item.app_user.phone }}</small><br />
						<small><b>Email:</b> {{ item.app_user.email }}</small><br />
						<small><b>Address:</b> {{ item.app_user.address }}</small><br />
						<small><b>Delivery State:</b> {{ item.app_user.delivery_state }}</small><br />
						
						<br />
						<small><b>Ordered Products:({{ item.app_user.order_id }})</small><br />
						<ul>
							{% for item2 in item.cart.product_quantitys.all %}
								<li>{{ item2.product.name }}({{ item2.quantity }})</li>
							{% endfor %}
						</ul>
						<br />
						<small><b>Total Price:</b> N{{ item.cart.total_price }}</small><br />
						<small><b>Order Note:</b> {{ item.order_note }}</small><br />
						<small><b>Payment Status:</b> {{ item.status }}</small>
						<hr>
						<br/><br/><br/><br />

					{% endfor %}
				{% endif %}
			</div>
				

			
		</div>

	</body>

</html>

main/templates/main/category.html
 {% extends 'main/base.html' %}
{% load static %}
  


{% block content %}
<div class="container text-centers">

<div class="ps-block--product-box">
    <br />
    <div class="ps-block__header">
        <h3><i class="icon-laundry"></i>#{{ category }} category</h3>
        <br />
    </div>
    <div class="container">
        <br />
        <p>To make it easy for you to navigate through our online store, we have carefully sorted out the categories. Select your furniture and proceed to place your order. We are always here to serve you better.</p>
     </div>
    <div class="ps-block__content">
        <div class="ps-block__left">
            <div class="ps-carousel--nav-inside owl-slider" data-owl-auto="true" data-owl-loop="true" data-owl-speed="5000" data-owl-gap="0" data-owl-nav="true" data-owl-dots="true" data-owl-item="1" data-owl-item-xs="1" data-owl-item-sm="1" data-owl-item-md="1" data-owl-item-lg="1" data-owl-duration="1000" data-owl-mousedrag="on">
                {% if category == 'living_room' %}
                    <a href="#"><img src="{% static 'main/img/lr.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/lr.png' %}" alt=""></a>

                {% elif category == 'kitchen' %}
                    <a href="#"><img src="{% static 'main/img/kt.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/kt.png' %}" alt=""></a>
                {% elif category == 'bedroom' %}
                    <a href="#"><img src="{% static 'main/img/br.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/br.png' %}" alt=""></a>

                    {% elif category == 'office' %}
                    <a href="#"><img src="{% static 'main/img/of.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/of.png' %}" alt=""></a>

                {% endif %}
            </div>
            <div class="ps-block__products ps-tab-root">
                <br />
                <p>A good furniture should add value to your space, spur happiness and give you comfort. We have them in different designs and colors in this category, check through and add your favorite furniture to your cart.
</p>
                <ul class="ps-tab-list">
                    <li class="current"><a href="#product-box-1">New Arrivals</a></li>
                </ul>
                <div class="ps-tabs">
                    <div class="ps-tab active" id="product-box-1">
                        <div class="row">
                            {% if product_one %}
                                {% for item in product_one %}
                                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4 col-6 ">
                                        <div class="ps-product">
                                            <div class="ps-product__thumbnail"><a href="{% url 'product:product_detail' item.slug %}"><img src="{{ item.image_1.url }}" alt=""></a>
                                                <div class="ps-product__badge">{{ item.tag_title }}</div>
                                                <ul class="ps-product__actions">
                                                    <li><a href="{% url 'cart:add_product_to_cart' item.slug %}" data-toggle="tooltip" data-placement="top" title="Add to cart"><i class="icon-bag2"></i></a></li>
                                                    <li><a href="#" data-placement="top" title="Quick View" data-toggle="modal" data-target="#{{ item.slug }}"><i class="icon-eye"></i></a></li>
                                                    <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-heart"></i></a></li>
                                                    <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-chart-bars"></i></a></li>
                                                </ul>
                                            </div>
                                            <div class="ps-product__container"><a class="ps-product__vendor" href="{% url 'product:product_detail' item.slug %}">{{ item.category }}</a>
                                                <div class="ps-product__content"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
                                                    <div class="ps-product__rating">
                                                        <select class="ps-rating" data-read-only="true">
                                                            <option value="1">1</option>
                                                            <option value="1">2</option>
                                                            <option value="1">3</option>
                                                            <option value="1">4</option>
                                                            <option value="2">5</option>
                                                        </select>
                                                    </div>
                                                    <p class="ps-product__price sale">₦{{ item.price }}<del>₦{{ item.old_price }} </del></p>
                                                </div>
                                                <div class="ps-product__content hover"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
                                                    <p class="ps-product__price sale">₦{{ item.price }}<del>₦{{ item.old_price }} </del></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}

                            {% else %}
                                <p>Sorry, Nothing Yet!</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ps-block__right">
            <figure>
                <figcaption>Recommended For You</figcaption>
                {% if product_two %}
                    {% for item in product_two %}
                        <div class="ps-product--horizontal">
                            <div class="ps-product__thumbnail"><a href="{% url 'product:product_detail' item.slug %}"><img src="{{ item.image_1.url }}" alt=""></a></div>
                            <div class="ps-product__content"><a class="ps-product__title" href="product-default.html">{{ item.name }}</a>
                                <p class="ps-product__price sale">N{{ item.price }}<del>N{{ item.old_price }}</del></p>
                            </div>
                        </div>
                    {% endfor %}

                {% else %}
                    <p>Sorry, Nothing Yet!</p>
                {% endif %}
            </figure>
            <br />
            <p>There are also other products in this category that you could request for. In addition to that, you can give us your specifications, in case you have special designs in mind. We deliver at the fastest speed you can ever imagine. You could just be coming in contact with your fondest and most reliable online furniture store.</p>
        </div>
    </div>
</div>
    
    <br />


</div>
</div>
</div>
<br><br><br>
<hr>


{% endblock %}

main/templates/main/index.html
{% extends 'main/base_new.html' %}
{% load static %}
      

{% block content %}

    <div id="homepage-7">

        <div class="ps-home-banner" style="margin-top: -30px; height: autof;">
            <div class="ps-carousel--nav-inside owl-slider" data-owl-auto="true" data-owl-loop="true" data-owl-speed="5000" data-owl-gap="0" data-owl-nav="true" data-owl-dots="true" data-owl-item="1" data-owl-item-xs="1" data-owl-item-sm="1" data-owl-item-md="1" data-owl-item-lg="1" data-owl-duration="1000" data-owl-mousedrag="on" data-owl-animate-in="fadeIn" data-owl-animate-out="fadeOut">
                <div class="ps-banner--autopart">
                    <img style="background-size: cover" src="{% static 'main/img/newbg1.png' %}">
                </div>
                <div class="ps-banner--autopart">
                   <img style="background-size: cover" src="{% static 'main/img/newbg2.png' %}">
                </div>
                <div class="ps-banner--autopart">
                   <img style="background-size: cover" src="{% static 'main/img/newbg3.png' %}">
                </div>
                <div class="ps-banner--autopart">
                   <img style="background-size: cover" src="{% static 'main/img/newbg4.png' %}">
                </div>
            </div>
        </div>
        <div class="ps-site-features" style="margin-top: -40px;">
            <div class="container">
                <div class="ps-block--site-features ps-block--site-features-2">
                    <div class="ps-block__item">
                        <div class="ps-block__left"><i class="icon-rocket"></i></div>
                        <div class="ps-block__right">
                            <h4>Free Delivery</h4>
                            <p>For all oders over $99</p>
                        </div>
                    </div>
                    <div class="ps-block__item">
                        <div class="ps-block__left"><i class="icon-sync"></i></div>
                        <div class="ps-block__right">
                            <h4>90 Days Return</h4>
                            <p>If goods have problems</p>
                        </div>
                    </div>
                    <div class="ps-block__item">
                        <div class="ps-block__left"><i class="icon-credit-card"></i></div>
                        <div class="ps-block__right">
                            <h4>Secure Payment</h4>
                            <p>100% secure payment</p>
                        </div>
                    </div>
                    <div class="ps-block__item">
                        <div class="ps-block__left"><i class="icon-bubbles"></i></div>
                        <div class="ps-block__right">
                            <h4>24/7 Support</h4>
                            <p>Dedicated support</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <br />
        
        
        <div class="ps-promotions ps-product-list ps-product-list--2">
            <div class="container">
                <br />
                <p>Market.iwlimited.com is your number one online furniture store. The environment is simplified to give you a better shopping experience. Please follow the categories and shop the best furniture for your Bedroom, Kitchen, Living room, Dining room, offices and lots more. From the product selection process to the payment, to the delivery and then installations, we make effort to give you maximum utility</p>
                <div class="ps-section__header">
                    <h3 style="color: grey;"><b>Top Categories:</b></h3>
                    <ul class="ps-section__links">
                        <li><a href="{% url 'main:category' 'kitchen' %}">Kitchen</a></li>
                        <li><a href="{% url 'main:category' 'living_room' %}">Living Room</a></li>
                        <li><a href="{% url 'main:category' 'office' %}">Office</a></li>
                        <li><a href="{% url 'main:category' 'bedroom' %}">Bedroom</a></li>
                    </ul>
                </div>
                <br />
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 "><a class="ps-collection" href="{% url 'main:category' 'office' %}"><img style="border-radius: 10px;" src="{% static 'main/img/office_cat.png' %}" alt=""></a>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 "><a class="ps-collection" href="{% url 'main:category' 'living_room' %}"><img style="border-radius: 10px;" src="{% static 'main/img/living_room_cat.png' %}" alt=""></a>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 "><a class="ps-collection" href="{% url 'main:category' 'kitchen' %}"><img style="border-radius: 10px;" src="{% static 'main/img/kitchen_cat.png' %}" alt=""></a>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 "><a class="ps-collection" href="{% url 'main:category' 'bedroom' %}"><img style="border-radius: 10px;" src="{% static 'main/img/bedroom_cat.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="ps-product-list ps-product-list--2">
            <div class="container">
                <div class="ps-section__header">
                    <h3 style="color: grey;"><b>Deal of the Day!</b></h3>
                    <ul class="ps-section__links">
                        <li><a href="{% url 'main:index' %}">New Arrivals</a></li>
                        <li><a href="{% url 'main:index' %}">Best seller</a></li>
                        <li><a href="{% url 'main:index' %}">Most Popular</a></li>
                        <li><a href="{% url 'main:index' %}">View All</a></li>
                    </ul>
                </div>
                <div class="ps-section__content">
                    <div class="ps-carousel--nav owl-slider" data-owl-auto="false" data-owl-loop="false" data-owl-speed="10000" data-owl-gap="0" data-owl-nav="true" data-owl-dots="true" data-owl-item="5" data-owl-item-xs="2" data-owl-item-sm="2" data-owl-item-md="2" data-owl-item-lg="3" data-owl-item-xl="5" data-owl-duration="1000" data-owl-mousedrag="on">
                        {% if section_one %}
                            {% for item in section_one %}
                                <div class="ps-product">
                                    <div class="ps-product__thumbnail"><a href="{% url 'product:product_detail' item.slug %}"><img src="{{ item.image_1.url }}" alt=""></a>
                                        <div class="ps-product__badge">{{ item.tag_title }}</div>
                                        <ul class="ps-product__actions">
                                            <li><a href="{% url 'cart:add_product_to_cart' item.slug %}" data-toggle="tooltip" data-placement="top" title="Add to cart"><i class="icon-bag2"></i></a></li>
                                            <li><a href="#" data-placement="top" title="Quick View" data-toggle="modal" data-target="#{{ item.slug }}"><i class="icon-eye"></i></a></li>
                                            <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-heart"></i></a></li>
                                            <li><a href="{% url 'product:product_detail' item.slug %}" data-toggle="tooltip" data-placement="top" title=""><i class="icon-chart-bars"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="ps-product__container"><a class="ps-product__vendor" href="{% url 'product:product_detail' item.slug %}">{{ item.category }}</a>
                                        <div class="ps-product__content"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
                                            <div class="ps-product__rating">
                                                <select class="ps-rating" data-read-only="true">
                                                    <option value="1">1</option>
                                                    <option value="1">2</option>
                                                    <option value="1">3</option>
                                                    <option value="1">4</option>
                                                    <option value="2">5</option>
                                                </select>
                                            </div>
                                            <p class="ps-product__price sale">₦{{ item.price }}<del>₦{{ item.old_price }} </del></p>
                                        </div>
                                        <div class="ps-product__content hover"><a class="ps-product__title" href="{% url 'product:product_detail' item.slug %}">{{ item.name }}</a>
                                            <p class="ps-product__price sale">₦{{ item.price }}<del>₦{{ item.old_price }} </del></p>
                                        </div>
                                    </div>
                                </div>
                                
                               {% endfor %}
                               
                               {% else %}
                                    <div class="ps-product">
                                        <p>Sorry, Nothing yet!</p>
                                    </div>
                                    
                            {% endif %}
                    </div>
                </div>
            </div>
            <br />
            <p class="container">Buying goods online is one of the most convenient ways a product can get to its user.  We have incorporated several strategies to our site to ensure that you get your desired furniture via the most convenient means possible. On our platform, we reduce the risk of associated with uncertainty of delivery of furniture to zero level and ensure transactions are well secured.</p>
        </div>
        <div class="ps-section--default ps-home-blog" style="background-color: #6f448b">
            <div class="container">
                <div class="ps-block--download-app" style="background-color: #6f448b">
                    <div class="ps-container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12 ">
                                <div class="ps-block__thumbnail"><img src="{% static 'main/img/gn5.png' %}" alt=""></div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12 ">
                                <div class="ps-block__content">
                                    <h3 style="color:#fff">Download market.iwlimited.com App Now!</h3>
                                    <p style="color:#fff">Have better shopping experience with our online store app.</p>
                                    <form class="ps-form--download-app">
                                        <div class="form-group--nest">
                                            <input class="form-control" type="Email" placeholder="Email Address">
                                            <button class="ps-btn">Subscribe</button>
                                        </div>
                                    </form>
                                    <p class="download-link"><a href="#"><img src="{% static 'main/img/google-play.png' %}" alt=""></a><a href="#"><img src="{% static 'main/img/app-store.png' %}" alt=""></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}